

name: Push Master

on:
  push:
    branches:
      - master

jobs:
  # Label of the container job
  ci-testing:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: testing_password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Imports data to database
        run: mysql --user=root --password=testing_password qa_db_ticketing < ./app/tests/_test_database.sql


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f testing-requirements.txt ]; then pip install -r testing-requirements.txt; fi


      - name: Lint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


      - name: Test 
        run: pytest
        env:
          DATABASE_HOST: mysql
          DATABASE_PASSWORD: testing_password
