name: Push Master
on:
  push:
    branches: ['master']

permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Generate new tag version
        id: version
        uses: flynshue/version-action@v0.0.1

      - name: Generate Lowercase Image Name
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{  steps.string.outputs.lowercase }}:${{ steps.version.outputs.version }}

      - name: "Generate changelog"
        id: changelog
        uses: Bullrich/generate-release-changelog@2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
        env:
          REPO: https://github.com/danielth-uk/QAC020X328K 

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          body: |
            ## Docker Image
            ```
            docker pull ghcr.io/danielth-uk/qac020x328k:${{ steps.version.outputs.version }}
            ```

            ## See Read Me for more information

            https://github.com/danielth-uk/QAC020X328K/blob/master/README.md

            ${{ steps.changelog.outputs.changelog }}

          makeLatest: true
          name: ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}

