

name: Push Master

env:
  ENV: CI
  DATABASE_HOST: mysql
  DATABASE_PASSWORD: testing_password
  DATABASE_DB: qa_db_ticketing
  DATABASE_USER: root
  JWT_SECRET: 4faa6ca2556c816cf63b88e84faa6ca2556c816cf63b88e89f6f3e7

on:
  push:
    branches:
      - master

jobs:
  # Label of the container job

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
      - name: Lint
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: testing_password
          MYSQL_DATABASE: qa_db_ticketing

        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Check out repository code
        uses: actions/setup-python@v3
        
      - name: Imports data to database
        run: mysql --user=root --password=testing_password -h 127.0.0.1 qa_db_ticketing < ./app/tests/_test_database.sql


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f testing-requirements.txt ]; then pip install -r testing-requirements.txt; fi
    
      - name: Test 
        run: |
          pip install pytest
          pytest